### ISSUE TITLE
When providing LHC with url containing query string parameters get double url encoded

### ISSUE THREAD

**Issue by Averethel** [local-ch/lhc#104]
```ruby
response = LHC.get("https://yellow--location-app--log-replays-on-cider.play.intra.local.ch/en/q?attribute=hospitality_foodspecial%3Abeer_tap&cat=1281&origin=46.303247%2C7.314001&rid=mWAm", error_handler: ->(_) { nil })
response.request.url

=> "https://yellow--location-app--log-replays-on-cider.play.intra.local.ch/en/q?attribute=hospitality_foodspecial%253Abeer_tap&cat=1281&origin=46.303247%252C7.314001&rid=mWAm"
```

When parsing query string and providing it via `params` option everything works as expected

**Comment by spape** [comment]
Try to pass parameters to params instead of trying to construct your own urls:
```ruby
LHC.request(
  url: "https://yellow--location-app--log-replays-on-cider.play.intra.local.ch/en/q",
  params: {
    attribute: "hospitality_foodspecial%3Abeer_tap",
    cat: 1281,
    origin: "46.303247%2C7.314001",
    rid: "mWAm"
  }
)
```

Otherwise, when I remember correctly, this happens on [Typhoeus::Easy](http://www.rubydoc.info/gems/typhoeus/0.4.2/Typhoeus/Easy) level.

So we can't really do much.

**Comment by Averethel** [comment]
I see. I remember I needed to do some weird checks when moving log replays to cider to avoid double encoding. I guess it's okay to close it now.

**Comment by spape** [comment]
https://github.com/local-ch/lhc/pull/113
