### ISSUE TITLE
Using long credentials creates invalid authorization header

### ISSUE THREAD

**Issue by JochenLutz** [local-ch/lhc#173]
I added authentication to my application with LHC::Auth.

My username is 15 characters long, the password has 32 characters. This results in an invalid authorization header, as Ruby's Base64#encode64 adds newlines after every 60 encoded characters (see [Ruby doc](https://www.rubydoc.info/stdlib/base64/Base64#encode64-class_method)).

    [...]
    Accept-Charset: utf-8
    Authorization: Basic XXXXxxxxXXXXxxxxXXXXxxxxXXXXxxxxXXXXxxxxXXXXxxxxXXXXxxxxXXXX
    xxxx
    [...]

Using `Base64::strict_encode64` should fix this issue.

**Comment by spape** [comment]
Addressed in https://github.com/local-ch/lhc/pull/179

Once reviewed I will release it as 12.0.3

Let me know if you should need a backport.

Thanks for reporting.

**Comment by spape** [comment]
https://github.com/local-ch/lhc/releases/tag/v12.0.3
