### ISSUE TITLE
Please use the standard SPDX ID for license in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [local-ch/lhc#176]
The current gemspec indicates that the license is GPL-3. It is not an SPDX standard one.

It should either be GPL-3.0 (https://spdx.org/licenses/GPL-3.0.html) - that is deprecated or (suggested) GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later.html).

Thanks!

**Comment by spape** [comment]
Fixed in https://github.com/local-ch/lhc/releases/tag/v12.0.2

Thanks for reporting 🙇

**Comment by mensfeld** [comment]
Thanks for working on this great gem! Thank you, looks great: https://my.diffend.io/gems/lhc/12.0.1/12.0.2

diffend no longer reports any problems with the license :fireworks: 

![Zrzut ekranu z 2020-07-13 17-27-14](https://user-images.githubusercontent.com/392754/87322806-2e0d1c00-c52e-11ea-9465-091397f8d938.png)
