### ISSUE TITLE
Get the effective url

### ISSUE THREAD

**Issue by tpreusse** [local-ch/lhc#38]
It would be nice to have a method to get the full effective url. Currently it is accessible from `typhoeus` via `response.request.raw.response.effective_url` but I assume thats is accidental.

The other existing API is `request.url` and `request.params` but this requires handling different types of params your self.

**Comment by pape-io** [comment]
As LHC was not following redirects by now, in which case you needed effective_url?
I enabled follow_location + effective_url with https://github.com/local-ch/lhc/pull/39

As soon as its merged there will a new `minor` version for it.

```
response = LHC.get('local.ch', follow_location: true)
response.effective_url
 => "http://www.local.ch/"
```

**Comment by pape-io** [comment]
Fixed in https://github.com/local-ch/lhc/releases/tag/v3.3.0

**Comment by tpreusse** [comment]
For me it was about query parameter serialization debugging (arrayFormat: indices vs. brackets vs. repeat) and to display the full url in development mode to collaborate with backend developers.

**Comment by tpreusse** [comment]
Thank you for adding it :+1:
