### ISSUE TITLE
data.to_json

### ISSUE THREAD

**Issue by pape-io** [local-ch/lhc#41]
`LHC.get().data` provides you a ruby object build with the response body data, that allows access with dot-notation.

Right now we use `OpenStruct` in order to make dot-notation access possible, but when you call `.to_json` on the `OpenStruct` `data` you do not end up with the original response body, as the marshaling of `OpenStruct` to json is 'special'.

Expected behaviour:

```
response = LHC.get()
expect(response.body).to eq response.data.to_json
```

**Comment by yannick** [comment]
fyi: probably related.
i get 
```Error undefined method `marshal_dump' for #<ActiveSupport::HashWithIndifferentAccess:0x007ff119132d08>``` 
when trying to  `LHC.json.get( params)["MyProp"]`

**Comment by pape-io** [comment]
@yannick you tried:
```ruby
LHC.json.get(params).data["MyProp"]
```

or are you able to also provide an example body?

**Comment by pape-io** [comment]
```ruby
LHC.json.get('https://api.ipify.org?format=json').data['ip']
```

**Comment by pape-io** [comment]
https://github.com/local-ch/lhc/pull/64

**Comment by pape-io** [comment]
BTW: @yannick which version?

**Comment by pape-io** [comment]
Improved in https://github.com/local-ch/lhc/releases/tag/v3.8.0

As in the provided example you were accessing the response directly, that was not a bug, but a missing feature. Therefor I close this case. @yannick
