### ISSUE TITLE
Double encoding of URL

### ISSUE THREAD

**Issue by acoiro** [local-ch/lhc#44]
Given 

```
params = { name: 'zürich' }
```

passing a URL with format

```
#{endpoint}?#{params.to_param}
```

to LCH will result in a double encode of the query string. `params.to_param` (or `params.to_query`) already encodes the parameters.

LHC line of interest https://github.com/local-ch/lhc/blob/master/lib/lhc/request.rb#L45
AMA issue https://github.com/local-ch/ama/blob/master/app/controllers/api/proxy_controller.rb#L54

**Comment by acoiro** [comment]
I'm fixing the AMA issue by replacing `params.to_param` with 

```
params.to_a.map { |x| "#{x[0]}=#{x[1]}" }.join('&')
```

I think it's up to the consumer to encode it, LHC shouldn't do it by default.

**Comment by gonzalocasas** [comment]
there was a good reason for this I think. 95b09c4e5c17a46e6dc5d92d18a6b86d4d4236a3

**Comment by acoiro** [comment]
Yep, I'm not convinced this is something a low level framework like LHC should handle.

**Comment by pape-io** [comment]
Thanks @gonzalocasas for intervening ;)

Let's start from the root problem: We had a double encoding issue in AMA cause we were constructing urls other self (glueing get parameters with host etc.). I was blindly taking this 'glueing-together' over when we moved if from cc proxy to AMA. The easy fix without changing anything in LHC is actually already prepared here: https://github.com/local-ch/ama/pull/40/files

I will take a little bit more time to write the argumentation why encoding should not happen, at least for the URL part, in LHC to close this issue.

**Comment by acoiro** [comment]
My bad, I forgot we can pass the param hash as a parameter. Maybe we should update the doc to prevent consumers to build the URL by themself.

**Comment by pape-io** [comment]
@acoiro all the examples in the docs use the explicit params option to pass params, but I will add a sentence about encoding, that includes not glueing together urls with parameters :+1:
