### ISSUE TITLE
Catch JSON parse errors and raise LHC::Errors instead.

### ISSUE THREAD

**Issue by maveonair** [local-ch/lhc#45]
When something went wrong with parsing the body as JSON then a JSON::ParserError is thrown here: https://github.com/local-ch/lhc/blob/master/lib/lhc/response.rb#L22-L26

This exception should actually be captured by LHC and a LHC::Error should be thrown which has the parse error as root cause. The reason for this approach is that I as a consumer I want rely on catching LHC::Errors so that I can act on those.

```ruby
def request
  result = LHC.json.get('my-awesome-api/users') # In the error case then this api returns HTML, which is bad it is that way...
  result.data
resque LHC::Error > error
  Rails.logger
  []
end
```

**Comment by pape-io** [comment]
Done https://github.com/local-ch/lhc/releases/tag/v3.5.0

Let me now if you need a backport
