### ISSUE TITLE
Endpoint cannot be compiled correctly

### ISSUE THREAD

**Issue by gonzalocasas** [local-ch/lhc#53]
This is a regression. Between versions 3.5.1 and 3.5.3 something (major?) changed on the endpoint parsing, and now the following setup doesn't work:

`config/initializers/lhc.rb`
```
LHC.config.placeholder(:datastore_host, 'http://somethingsomething')
LHC.get(:admin_by_device_id, params: { device_id: device_id })
```

When trying to get that endpoint:
```
response = LHC.get(:admin_by_device_id, params: { device_id: device_id })
```

I get `Compilation incomplete. Unable to find value for device_id.json.`

**Comment by pape-io** [comment]
Will need to check into that one. Which application? Extapi?

**Comment by pape-io** [comment]
Can confirm a regression. Major change was not intended. So we will patch it.

I discovered similiar problems with entry endpoints recently, because they include `.json` e.g. `/entries/:id.json`. That's seems to be an edge case that stopped working. I will add this case to the tests.
