### ISSUE TITLE
LHC: Monitoring / Caching Interceptor (make it possible to distinguish responses served from cache)

### ISSUE THREAD

**Issue by skaestle** [local-ch/lhc#86]
# Problem

When using the monitoring interceptor on an LHC instance that also uses the Caching interceptor you may get a skewed picture, because the monitoring interceptor has no way of knowing whether the request was served by the cache or not

# Solution

- [ ] annotate the response with the information whether it was served by cache or not (HTTP headers?)
- [ ] decide on the best behavior of Monitoring interceptor in regards to cached responses (should they even be reported, and if so in what manner)

**Comment by spape** [comment]
Adressed here: https://github.com/local-ch/lhc/pull/88
@skaestle can you make a second issue for your second point in solutions: "How to deal with monitoring now"
